import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <h2>Client-side transitions, no live regions</h2>
        <ul>
          <li>
            <Link href="/clientside/nolive/1">
              <a>Manchester Picadilly</a>
            </Link>
          </li>
          <li>
            <Link href="/clientside/nolive/1">
              <a>Manchester Victoria</a>
            </Link>
          </li>
        </ul>

        <h2>Client-side transitions, with live regions</h2>
        <ul>
          <li>
            <Link href="/clientside/live/1">
              <a>Manchester Picadilly</a>
            </Link>
          </li>
          <li>
            <Link href="/clientside/live/1">
              <a>Manchester Victoria</a>
            </Link>
          </li>
        </ul>

        <h2>Full reload transitions, no live regions</h2>
        <ul>
          <li>
            <Link href="/fullpage/nolive/1">
              <a>Manchester Picadilly</a>
            </Link>
          </li>
          <li>
            <Link href="/fullpage/nolive/1">
              <a>Manchester Victoria</a>
            </Link>
          </li>
        </ul>

        <h2>Full reload transitions, with live regions</h2>
        <ul>
          <li>
            <Link href="/fullpage/live/1">
              <a>Manchester Picadilly</a>
            </Link>
          </li>
          <li>
            <Link href="/fullpage/live/1">
              <a>Manchester Victoria</a>
            </Link>
          </li>
        </ul>
      </nav>
    </div>
  );
}
